### ISSUE TITLE
Share repositories with maven

### ISSUE THREAD

**Issue by uklance** [wfhartford/gradle-maven-thief#2]
Parse ~/.m2/settings.xml and ~/.m2/settings-security.xml to get repositories, usernames and passwords
@see [maven-settings-decoder](https://github.com/jelmerk/maven-settings-decoder) for decrypting passwords

**Comment by wfhartford** [comment]
Sharing repository settings with maven represents quite a bit of added complexity to the plugin, and I do not see a lot of value. The main use case for this plugin is to keep a gradle build synchronised with its maven counterpart through ongoing development. Most things in the settings.xml file do not change frequently enough to warrant synchronisation via a plugin.

That of course is just my opinion, if you think it would be valuable, I would accept a pull request. Just a few things to keep in mind if you decide to work on it:
- Allow repositories in the build.gradle file to override those pulled in from settings.xml.
- Maven has the concept of mirror repositories, with potentially complex rules, which I don't think gradle supports.
- Configuring gradle to publish artifacts to maven repositories can be quite complex, especially when considering mavens distinction between release and snapshot repositories.

**Comment by uklance** [comment]
Agreed, there's also a chicken and egg issue because you need a repo to apply the plugin in the first place. I started using your plugin but then needed it to be more customizable. 

I've just created a similar plugin that I dubbed [gradle-maven-share](https://github.com/uklance/gradle-maven-share) that allows for custom share actions, largely inspired by the gradle-maven-thief plugin.

Cheers,
Lance
